project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!readme.md"

title-block-banner: assets/giskurs_header_s_t.png
title-block-banner-color: black
title-block-style: default

website:
  title: "GIS LOEK"
  sidebar:
    style: floating
    search: false
    contents:
      - text: Home
        href: index.qmd
      - section: Geographische Daten
        contents:
          - href: daten-erheben.qmd
            text: Daten erheben
          - href: webservices.qmd
            text: Webdienste
          - href: projectionen.qmd
            text: Projektionen
      - section: GIS Grundlagen
        contents:
          - href: vector-basics.qmd
            text: Vektor Basics
          - href: raster-basics.qmd
            text: Raster Basics
          - href: raster-vector-basics.qmd
            text: Raster-Vektor Interaktionen
      - section: Habitatanalysen
      - section: Geländeanalysen
        contents:
          - href: topography.qmd
            text: Digitale Geländemodelle
          - href: hydrology.qmd
            text: Hydrologische Analysen
      - text: Kostenanalyse
        href: kostenanalyse.qmd



format:
  html:
    theme: cosmo
    css: "assets/style.css"
