project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!readme.md"

title-block-banner: assets/giskurs_header_s_t.png
title-block-banner-color: black
title-block-style: default

website:
  title: "GIS4LOEK"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Geographische Daten
        menu:
          - text: Daten erheben
            href: daten-erheben.qmd
          - text: Webdienste
            href: webservices.qmd
      - text: GIS Basics
        menu:
          - text: Vektor Basics
            href: vector-basics.qmd
          - text: Raster Basics
            href: raster-basics.qmd
          - text: Raster-Vektor Basics
            href: raster-vector-basics.qmd
      - href: topography.qmd
        text: Geländeanalysen
      - href: kostenanalyse.qmd
        text: Kostenanalyse
      - href: Projektarbeit.qmd
        text: GIS Projekt






format:
  html:
    theme: cosmo
    css: "assets/style.css"