---
title: Vektor-Basics
---

## Vorlesung

<embed src="slides/02a_Vektorbasics.pdf" type="application/pdf" width="100%" height="500">

## Das Vektordatenmodell

Bevor wir in die Praxis einsteigen, ein kurzer theoretischer Rückblick: Ein Datenmodell dient dazu, die reale Welt im GIS repräsentieren zu können. Da die Realität zu komplex ist, erfolgt dies durch eine Abstraktion. Je nachdem, ob wir diskrete Objekte (z. B. Bäume, Flüsse, Naturschutzgebiete) betrachten oder kontinuierliche Felder (z. B. Lufttemperatur, Höhe), bieten sich zwei verschiedene Datenmodelle an.

In dieser Woche konzentrieren wir uns zunähst auf das Vektormodell, das Koordinatenpaare (x, y) nutzt, um geografische Objekte zu beschreiben. Da wir hier von diskreten Objekten sprechen, bedeutet dies, dass die Objekte klar definierte Grenzen haben und als einzelne, voneinander trennbare Einheiten existieren.

Wir unterscheiden dabei drei grundlegende Geometrietypen:

- Punkt: Ein einzelner Koordinatenpunkt (z. B. ein Messstandort, ein einzelner Baum).
- Linie (Polyline): Eine Folge von Punkten, die durch Segmente verbunden sind (z. B. Bachläufe, Wanderwege).
- Polygon: Eine geschlossene Linie, die eine Fläche umschließt (z. B. Waldgebiet, Stadtbezirk).

Vektordaten erlauben die direkte Verknüpfung der geometrie mit einer Attributtabelle, in der alle nicht-geometrischen Informationen (z. B. Baumart, pH-Wert, Flächennutzung) gespeichert werden.



## Vektoroperationen

## Übung

:::{.callout-tip}
## Aufgabe
Lade das [Baumkataster](https://opendata.stadt-muenster.de/dataset/digitales-baumkataster-m%C3%BCnster/resource/096c4fc2-cfdb-4b9b-840f-da9e638e65ec), das [Geo1](https://uni-muenster.sciebo.de/s/dwzzsNBSAs5xBW9) und die [Stadtgrenzen von Münster](https://opendata.stadt-muenster.de/sites/default/files/05515000_shp_stadtbezirk.zip) herunter. Beantworte folgende Fragen:

1. Wieviele Eichen stehen im Münster Mitte?

2. Wo steht die nächstgelegende Birke vom Geo1 (Tip: z.B. Distance Matrix)

:::



