---
title: Ex03 - Webdienste
format: pdf
---

# Aufgaben - Datenformate und Webdienste



## Webdienste

Was ist der konzeptionelle Unterschied zwischen dem Web Map Service (WMS) und dem Web Feature Service (WFS)?



## Web Map Tile Service


Das Bundesamt für Kartographie bietet einem Web Map Tile Service für Geländemodelldaten an: [WMTS Geländekarte des BKG](https://gdz.bkg.bund.de/index.php/default/wmts-basemapde-schummerung-wmts-basemapde-schummerung.html)

- Welche drei Produkte werden von dem Geländedaten-Dienst bereitgestellt?
- Welche Datenbasis nutzt der Geländedaten-Dienst zur Berechnung der Produkte? Wie hoch ist die räumliche Auflösung?

- Binden Sie den Dienst in QGIS ein. 
- Jedes der drei Produkte gibt es in vier Versionen. Wodurch unterscheiden sich diese Versionen?



## Vorbereitung: Projektionen

Im Wintersemester 2014 / 2015 hat Matthias Rüster an der Hochschule Anhalt im Modul Liegenschaftswesen eine Hausarbeit zum Thema "Umstellung GK zu ETRS89/UTM: Auswirkungen auf das Kataster" geschrieben. Er hat die Arbeit auf seiner Homepage veröffentlicht: [https://www.m13r.de/Studium/LW-Seminar-201415-Matthias-R%C3%BCster.pdf](https://www.m13r.de/Studium/LW-Seminar-201415-Matthias-R%C3%BCster.pdf)

- Lesen Sie die Arbeit.
- Wie bewerten Sie die Arbeit? Was ist positiv, was negativ?
- Was bedeutet GK? Was bedeutet ETRS89? Und warum wurde Umgestellt?
- Notieren Sie sich offene Fragen und Diskussionspunkte die wir im Plenum diskutieren können.







