---
title: Ex03 - Projektionen
format: pdf
---



## Arktische Fauna


Auf `naturalearthdata.com` gibt es grundlegende Vektordaten für karthographische Zwecke. Laden Sie die Küstenlinien über folgenen Link herunter: [https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/physical/ne_50m_coastline.zip](https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/physical/ne_50m_coastline.zip).
Und über folgenden Link die Ozeane mit Label: [https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/physical/ne_50m_geography_marine_polys.zip](https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/physical/ne_50m_geography_marine_polys.zip)
Und über folgenden Link [https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/physical/ne_50m_geographic_lines.zip](https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/physical/ne_50m_geographic_lines.zip) geographische Linien zur besseren Orientierung.


- In welchem Koordinatensystem liegen die Daten vor?
- Visualisiere die Küstenlinien und die Ozeane sinnvoll.
- Für die Ozeane sollen nur die Label sichtbar sein (Spalte 'name' der Attributtabelle).


Papageientaucher (*Fratercula arctica*) und Krabbentaucher (*Alle Alle*) haben ihr Hauptverbreitungsgebiet in der Arktis.
Auf der Kollaborative Plattform [gbif.org](https://www.gbif.org/) werden Artbeobachtungen gesammelt und können dort heruntergeladen werden.
Hier ist ein Datensatz, mit den Beobachtungen der beiden Arten in den Jahren 2024 und 2025: XXX

- Visualisieren Sie den Datensatz. 
- Nutzen Sie dafür ein Koordinatenbezugssytem, welches auf die Arktis angepasst ist.
- Wie unterscheidet sich das Verbreitungsgebiet der beiden Arten?
- Gibt es einen Unterschied zwischen 2024 und 2025?




## Vorbereitung Vektordaten

In der nächsten Einheit wird es um Vektoroperationen gehen. Zur Vorbereitung frischen Sie ihre Kenntnisse gängiger Werkzeuge auf. Lesen Sie dazu den Website Text zu den Vektordaten.

### Thematische Abfragen
Stellen Sie sich vor, Sie arbeiten mit einem Vektordatensatz von Beobachtungen verschiedener Tierarten in einem Nationalpark. Jedes Objekt (Punkt) ist mit einer Attributtabelle verknüpft, die unter anderem die Spalten Art, Gewicht (in kg) und Status (z. B. 'gefährdet', 'stabil') enthält.

Ein Kollege hat eine Abfrage erstellt, um eine bestimmte Gruppe von Tieren für eine Analyse zu selektieren. Der Ausdruck im Editor sieht wie folgt aus:

```sql
"Gewicht" > 400 AND ("Art" = 'Elefant' OR "Art" = 'Nashorn')
```

Analysieren Sie diesen Ausdruck und beantworten Sie die folgenden Fragen:

- Wie viele Vergleichsoperatoren können Sie identifizieren? Welche sind es?
- Wie viele logische Operatoren kommen vor? Welche sind es?
- Formulieren Sie diesen formalen Ausdruck in eine normale, fachliche Frage um. Was genau möchte der Kollege mit dieser Abfrage finden?


### Vektorverarbeitung
In QGIS gibt es in der oberen Menüleiste den Eintrag "Vektor" und darin die Rubrik "Geoprocessing Tools". Dort sind unter anderem die Werkzeuge

- Puffer / Buffer
- Clip
- Difference
- Dissolve
- Intersection

Beschreiben Sie kurz was diese Werkzeuge machen und überlegen Sie sich zu 3 der Werkzeuge einen potentiellen Anwendungsfall mit landschaftsökologischem Bezug.

